In [66]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import numpy as np
from sklearn.metrics import f1_score

In [67]:
iris = load_iris()
X, y, iris_classes = iris.data, iris.target, iris.target_names

In [68]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [69]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [70]:
y1 = pd.get_dummies(y).values
y1

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [71]:
X_train, X_test, y1_train, y1_test = train_test_split(X, y1, test_size=0.2, random_state=0)

In [82]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(30, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

In [83]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['categorical_accuracy'])

In [84]:
model.fit(X_train, y_train, batch_size=50, epochs=50)

Epoch 1/50


D:\Kodilla\kurs_pythona\lib\site-packages\keras\backend.py:5534: UserWarning: "`categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


3/3 [==============================] - 1s 9ms/step - loss: 1.6837 - categorical_accuracy: 0.3667
Epoch 2/50
3/3 [==============================] - 0s 4ms/step - loss: 1.4825 - categorical_accuracy: 0.3667
Epoch 3/50
3/3 [==============================] - 0s 4ms/step - loss: 1.3141 - categorical_accuracy: 0.3667
Epoch 4/50
3/3 [==============================] - 0s 3ms/step - loss: 1.2185 - categorical_accuracy: 0.3667
Epoch 5/50
3/3 [==============================] - 0s 5ms/step - loss: 1.1719 - categorical_accuracy: 0.3917
Epoch 6/50
3/3 [==============================] - 0s 4ms/step - loss: 1.1488 - categorical_accuracy: 0.4167
Epoch 7/50
3/3 [==============================] - 0s 4ms/step - loss: 1.1121 - categorical_accuracy: 0.4250
Epoch 8/50
3/3 [==============================] - 0s 3ms/step - loss: 1.0646 - categorical_accuracy: 0.5333
Epoch 9/50
3/3 [==============================] - 0s 2ms/step - loss: 1.0264 - categorical_accuracy: 0.5333
Epoch 10/50
3/3 [======================

In [85]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 113ms/step


array([[0.00341605, 0.11588841, 0.8806955 ],
       [0.07500186, 0.6714069 , 0.25359115],
       [0.94596356, 0.04922993, 0.00480647],
       [0.00528673, 0.22609702, 0.7686162 ],
       [0.9081855 , 0.08182724, 0.00998725],
       [0.00143602, 0.0720021 , 0.92656195],
       [0.9176725 , 0.07296774, 0.00935969],
       [0.04284742, 0.5951063 , 0.36204624],
       [0.03668811, 0.60302967, 0.3602822 ],
       [0.07978807, 0.6492322 , 0.2709797 ],
       [0.01073877, 0.2427809 , 0.7464803 ],
       [0.05156612, 0.58395416, 0.36447963],
       [0.04004521, 0.53566414, 0.4242906 ],
       [0.03725536, 0.5594757 , 0.40326896],
       [0.03373274, 0.48300734, 0.4832599 ],
       [0.92397326, 0.06785002, 0.00817665],
       [0.03667777, 0.48184454, 0.4814777 ],
       [0.03997631, 0.46695766, 0.49306595],
       [0.8711746 , 0.11334712, 0.0154783 ],
       [0.93381554, 0.05948502, 0.0066994 ],
       [0.007319  , 0.17691529, 0.81576574],
       [0.0324064 , 0.40102467, 0.566569  ],
       [0.

In [86]:
actual = np.argmax(y1_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")


Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 2 0 1 2 0 0 2 2 0 0 2 0 0 1 1 0]


In [87]:
f1 = f1_score(actual, predicted, average='micro')
f1

0.9